name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT_ID: peppy-vertex-434912-m1
  GCP_REGION: asia-northeast1
  IMAGE_NAME: gcr.io/peppy-vertex-434912-m1/backend-backend-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with: 
          version: 'latest'

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          TAG=$(echo $GITHUB_SHA | head -c7)
          docker build -t ${IMAGE_NAME}:${TAG} .
          docker push ${IMAGE_NAME}:${TAG}

      - name: Debug Information
        run: |
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "IMAGE_NAME: $IMAGE_NAME"
          TAG=$(echo $GITHUB_SHA | head -c7)
          echo "TAG: $TAG"
          gcloud info
          docker images

      - name: Deploy to Cloud Run
        run: |
          TAG=$(echo $GITHUB_SHA | head -c7)
          gcloud run deploy jobreco-api \
            --image ${IMAGE_NAME}:${TAG} \
            --platform managed \
            --region ${GCP_REGION} \
            --allow-unauthenticated \
            --set-env-vars DATABASE_URL='${{ secrets.DATABASE_URL }}' \
            --set-env-vars TZ='Asia/Tokyo' \
            --ingress internal-and-cloud-load-balancing # Cloud Load Balancing 経由のアクセスのみを許可

      - name: Output error logs
        if: failure()
        run: |
          gcloud run revisions list --service=jobreco-api --region=${GCP_REGION} --format='value(name)' | head -n 1 | xargs -I {} gcloud run logs read --region=${GCP_REGION} --service=jobreco-api --revision={}
